// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSyxBD9FXba0f_vt4cwHuglmHRPbLFFNs',
    appId: '1:67441311343:web:5ac8a197aec3420a45d79a',
    messagingSenderId: '67441311343',
    projectId: 'hackthon2026-aa0ae',
    authDomain: 'hackthon2026-aa0ae.firebaseapp.com',
    storageBucket: 'hackthon2026-aa0ae.firebasestorage.app',
    measurementId: 'G-NW84H3GYM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpy2gvlyxkg_0JHmocQ_pxwb4GHzJB1Dg',
    appId: '1:67441311343:android:b8adcc3c8f729a8045d79a',
    messagingSenderId: '67441311343',
    projectId: 'hackthon2026-aa0ae',
    storageBucket: 'hackthon2026-aa0ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEGLRJWRcEvtgQKCsqZ2FYfFp5qOQO9sg',
    appId: '1:67441311343:ios:674f9de1f7740fdc45d79a',
    messagingSenderId: '67441311343',
    projectId: 'hackthon2026-aa0ae',
    storageBucket: 'hackthon2026-aa0ae.firebasestorage.app',
    iosBundleId: 'com.example.durgaPujaPandel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEGLRJWRcEvtgQKCsqZ2FYfFp5qOQO9sg',
    appId: '1:67441311343:ios:674f9de1f7740fdc45d79a',
    messagingSenderId: '67441311343',
    projectId: 'hackthon2026-aa0ae',
    storageBucket: 'hackthon2026-aa0ae.firebasestorage.app',
    iosBundleId: 'com.example.durgaPujaPandel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSyxBD9FXba0f_vt4cwHuglmHRPbLFFNs',
    appId: '1:67441311343:web:cf75692cd9d6d2f645d79a',
    messagingSenderId: '67441311343',
    projectId: 'hackthon2026-aa0ae',
    authDomain: 'hackthon2026-aa0ae.firebaseapp.com',
    storageBucket: 'hackthon2026-aa0ae.firebasestorage.app',
    measurementId: 'G-CHGWVLG5BE',
  );
}
